theme: jekyll-theme-slate
title: jrummell.ToString()
description: Another .NET blog
google_analytics: UA-20232883-1
comments: true
twitter_username: jrummell
github_username:  jrumell
page_paths:
  - archive.md
  - projects.md
disqus:
  shortname: jrummell
defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default"
