theme: jekyll-theme-slate
title: jrummell.ToString()
description: Another .NET blog
google_analytics: UA-20232883-1
comments: true
twitter_username: jrummell
github_username:  jrummell
page_paths: [archive.md, projects.md]
disqus_shortname: jrummell
defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default"
plugins:
  - jekyll-redirect-from
