theme: jekyll-theme-slate
title: jrummell.ToString()
description: Another .NET blog
defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default"
